/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.cathoappfoodtruckback.service.api.controller;

import com.example.cathoappfoodtruckback.service.api.model.Error;
import com.example.cathoappfoodtruckback.service.api.model.ResponseDessertDTO;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.context.request.NativeWebRequest;

import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Api(value = "Dessert", description = "the Dessert API")
public interface DessertApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /v1/dessert/all : get all Desserts
     * get all Desserts
     *
     * @return Successful response - returns an array of &#x60;DessertDTO&#x60; entities. (status code 200)
     *         or Bad request (status code 400)
     */
    @ApiOperation(value = "get all Desserts", nickname = "getDesserts", notes = "get all Desserts", response = ResponseDessertDTO.class, tags={ "Dessert", })
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Successful response - returns an array of `DessertDTO` entities.", response = ResponseDessertDTO.class),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class) })
    @GetMapping(
        value = "/v1/dessert/all",
        produces = { "application/json" }
    )
    default ResponseEntity<ResponseDessertDTO> getDesserts() {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"data\" : [ { \"note\" : 1, \"id_boisson\" : 0, \"prix\" : 6, \"description\" : \"description\", \"nom\" : \"nom\", \"url_image\" : \"url_image\" }, { \"note\" : 1, \"id_boisson\" : 0, \"prix\" : 6, \"description\" : \"description\", \"nom\" : \"nom\", \"url_image\" : \"url_image\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
